### ISSUE TITLE
Error loading package in 3.6.1

### ISSUE THREAD

**Issue by lambdata30** [isubirana/compareGroups#12]
I recently upgraded R to 3.6.1. 

I am unable to install compareGroups as haplo.stats will not install. Please see the error below.
Would you happen to have a work around this - besides downgrading to an earlier version of R.

Thanks a lot!

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

[R.app GUI 1.70 (7684) x86_64-apple-darwin15.6.0]

> install.packages('compareGroups')
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6/compareGroups_4.2.0.tgz'
Content type 'application/x-gzip' length 3591896 bytes (3.4 MB)
==================================================
downloaded 3.4 MB
The downloaded binary packages are in
	/var/folders/br/536b2n2n6bxf_qvfyk5b0pph0000gn/T//Rtmps0rQcj/downloaded_packages
> library('compareGroups')
Loading required package: SNPassoc
Loading required package: haplo.stats
Error: package or namespace load failed for ‘haplo.stats’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’
Error: package ‘haplo.stats’ could not be loaded

**Comment by isubirana** [comment]
Could you provide the sessionInfo() you are using?

According to the error message you got, installing or reinstalling data.table package might solve your problem.

**Comment by slambooy00** [comment]
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1

**Comment by slambooy00** [comment]
Thanks for the response. I re-installed data.tables. However I am now getting a different error.

Perhaps it has something to do with macOS Catalina?

> library(compareGroups)
Loading required package: SNPassoc
Loading required package: haplo.stats
Loading required package: survival
Loading required package: mvtnorm
Loading required package: parallel
Registered S3 method overwritten by 'SNPassoc':
  method            from       
  summary.haplo.glm haplo.stats
Error: package or namespace load failed for ‘compareGroups’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found
> library(data.table)
data.table 1.12.6 using 2 threads (see ?getDTthreads).  Latest news: r-datatable.com
>

**Comment by isubirana** [comment]
I am not sure, but maybe install or reinstalling systemfonts package could solve the problem.

```
install.packages('systemfonts')
```

**Comment by umbertomig** [comment]
Hi, I'm having the same problem. I tried the `install.packages('systemfonts')` but for me, it didn't help.

**Comment by lambdata30** [comment]
I ended up re-installing catalina and xcode and that seem to fix the problem. I can now install and run compareGroups in Rstudio  and R. Currently running the following versions: Mac OS X 10.15.2 ; Xcode : 11.3. Hope that helps @umbertomig

**Comment by tuanvnguyen** [comment]
I also have the same problem of installation. I run R in MacOS (Catalina). The message is:

> library(compareGroups)
Loading required package: SNPassoc
Loading required package: haplo.stats
Loading required package: survival
Loading required package: mvtnorm
Loading required package: parallel
Registered S3 method overwritten by 'SNPassoc':
  method            from       
  summary.haplo.glm haplo.stats
Error: package or namespace load failed for ‘compareGroups’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found

**Comment by chymkat** [comment]
Dear All

I am getting this problem using windows but not mac, I do run also the systemfonts but no success. Please advise.

package ‘compareGroups’ successfully unpacked and MD5 sums checked
> library(compareGroups)
Error: package or namespace load failed for ‘compareGroups’ in namespaceExport(ns, exports):
 undefined exports: cividis, inferno, magma, mako, plasma, rocket, turbo, viridis, viridis.map, viridisMap
