### ISSUE TITLE
Loading Package after update to R version  3.6.3

### ISSUE THREAD

**Issue by MatRapi** [isubirana/compareGroups#14]
Hello everyone,

I am having the issue to load the compareGroups package after updating to R version 3.6.3 and re-installation of all other packages (which load and work all fine). 

Session Info:

###
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6
###

Here is part of the error message ( I apologize some of it is in German…):
###
Fehler: package or namespace load failed for ‘compareGroups’ in dyn.load(file, DLLpath = DLLpath, ...):
kann shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found
###

I did try to re-install system.fonts as mentioned here (https://github.com/isubirana/compareGroups/issues/12) and restarted my Mac, but this did not solve the problem.

Is there a Mac-user that could help with this problem?

Thanks a lot!

Mat

**Comment by isubirana** [comment]
If you install the XQuartz software in your Mac (https://www.xquartz.org/) you should be able to install compareGroups with no problems.
Let me know if it works.
