### ISSUE TITLE
export2word error

### ISSUE THREAD

**Issue by saisaitian** [isubirana/compareGroups#15]
when i use export2word function, it always get error. Could you help me fix it? Thank you!
![image](https://user-images.githubusercontent.com/26356557/80296303-4f226400-87ac-11ea-909b-6ccc3dbb50e6.png)

**Comment by isubirana** [comment]
Could you provide your **`sessionInfo()`**? 
It might be a problem of `pandoc` and R package `rmarkdown` versions.
