### ISSUE TITLE
trouble with ccclon function from ccrm package (fewer observations than random effects in all level 1 groups)

### ISSUE THREAD

**Issue by ecurueil2** [isubirana/compareGroups#16]
Hello,
I have one question concerning programming with "R" - ccclon-function from cccrm-package (Concordance Correlation Coefficient for Repeated (andNon-Repeated) Measures).

I created the long format for my child data "child_long" (via pivot_longer)
- with "assayresults" as the numeric outcome of a laboratory measurement (n=2957), "lfd_Nr" as biunique index, "visnr" as the number of study visit (1 to 6), "assay" as character vector consisting of four different methods and the covar "CH_age".

```
result<-ccclon(child_long,
       ry="assayresults",
       rind= "lfd_Nr",
       rtime="visnr",
       rmet="assay",
       covar="CH_age", 
       rho=0,
       cl=0.95)
```

After entering the "formula", I recieve the warning:
"Fehler in lme.formula(form, dades, random = list(ind = pdBlocked(list(~1,  : 
fewer observations than random effects in all level 1 groups"."

What is the level 1 group in my case? What could I change for receiving a result?

And why do I always get an error when entering a second item for covar (whatever the item is (like "CH_gender" and not "CH_age") - alone it seems to work - except there is the warning from above)? A syntax problem for covar?

Thank you a lot!

**Comment by isubirana** [comment]
I am not sure if you question refers to compareGroups package. 
Please, could you provide an example where a compareGroups functions is involved?

**Comment by ecurueil2** [comment]
Thank you for your advice! Excuse me for my late answer, please.

I think, there was a mistake because the variable for rind should not be biunique but should contain the ID of study probands - that is the same in all repeats (study follow-up visits).

**Comment by ecurueil2** [comment]
I try explain again more simple:
I have data from a child study cohort. Some children took part more than one time (only in different years - at different ages). Children always have the same "ID" (see below rind) but "visitnumber" ranges from 1 to 4 (see rtime). In that special case, I would like to compare (for all visits from all probands), the values of two different measuring methods (rmet=method, ry=methodresult) for the same blood parameter. Because I would like to include all follow-up-visits of children (repeat), I chose cccrm-package (repeated measures concordance correlation coefficient).

a<-ccclon(child,
           ry="methodresult",
           rind= "ID",
           rtime="visitnumber",
           rmet="method",
           covar=NULL, 
           rho=0,
           cl=0.95)
Thereafter, I recieve the warning: error in ccclon(child, ry = "methodresult", rind = "ID", rtime = "visitnumber", : Non-positive definite approximate variance-covariance

What could I change here?

If I add fixed effects for covar, warnings remain :

... covar="sex",...
same warning as above

...covar="age"...
warning: error in C[, k] <- c(1, contrasts(dades$met)[i, ], contrasts(dades$time)[j, : number of elements to be replaced is not a multiple of replacement length

...covar="age", "sex"...
unused argument ("sex")

Thank you in advance for any advice!

**Comment by isubirana** [comment]
I think this issue is not related to compareGroups functions
