### ISSUE TITLE
Plot percentages : plot.createTable with type = 1 ?

### ISSUE THREAD

**Issue by prise6** [isubirana/compareGroups#2]
Hi, 

Great package ! Love it.

Could you confirmed there's no easy way to plot percentage for categorical variable ?
I think frequencies aren't always relevant.

regards.

**Comment by isubirana** [comment]
Thank you very much for using the compareGroups packages.

This is a requested we had from other users. And we incorporated this options in the newest newest version (4.0.0) from available on github. We have incorporated other major improvements. Hopely it will be available on CRAN very soon.

Returning on your question, you just have to specify **`perc`** options in the **`plot`** mehod. Following, there is an example with regicor data set:

```
res <- compareGroups(year~. , regicor)
# percentages without distinguishing groups (years)
plot(res['sex'], perc = TRUE)

# by year. It plots percentages of women/men within groups (years)
plot(res['sex'], bivar=TRUE, perc = TRUE)
```

**Comment by xmarti6** [comment]
Hi, how the option "perc=TRUE" could be included in "report()" function?
Thank you
