### ISSUE TITLE
Using compareGroups tables in Rmarkdown to PDF

### ISSUE THREAD

**Issue by kambanane** [isubirana/compareGroups#21]
Is there any good way to use tables from compareGroups with Rmarkdown for PDF? 

1. They are usually so wide they get cut off.
2. Is there a way to change the fonts?
3. Categorical variables are fully left justified. 

Do you know of any things that other people might have tried?

**Comment by isubirana** [comment]
By now, it is not possible to fully customize the descriptive tables when exporting to PDF by compareGroups package.
In order to try to improve this issues, could you provide an example showing the points you request?
Thanks.

**Comment by kambanane** [comment]
ok, I will find another way then. It would be great if it becomes possible sometime in the future. thanks

**Comment by isubirana** [comment]
Ok. We will try to add some issues to improve the table customization when exporting to PDF.

**Comment by kambanane** [comment]
I see that this is closed, has something been done to solve this problem? If so, could I have some details?

**Comment by isubirana** [comment]
Sorry for not giving news about it and for closing the topic. 
Since then, we haven't been able to make much progress on the points you required. Just say that you can decrease or increase the font size using the `size` argument from `export2md` or `export2pdf` functions. 
I hope this can fix partially the problem of wide tables.

Regards,

Isaac.

**Comment by hsbizahlenzauber** [comment]
Thanks for the great package! export2md makes it easy to use with RMD.

For my workflow with RMD, it would be helpful to have an additional function that exports the table in data frame format. This way, I could utilize the functionalities of the kable and kbl packages when I need to customize the output.

Even though one of the advantages of compareGroups is to deliver pretty tables instantly, I occasionally need to customize the appearance. Maybe this feature would help in the cases described by @kambanane.

Regards,
Thomas

**Comment by isubirana** [comment]
Hi,

First of all, I'm glad you fing compareGroups package useful to create rmd reports.

Anwering to your question, when exporting to PDF or HTML, export2md uses knitr and kableExtra functions. Therefore, the resulting object created by export2md function is from kable class, and you should be able to costumize them by knitr and kableExtra functions (such as removing a column o changing the color of a row or a column, etc.). 
Anyway, let me know if any modification you want to perform using knitr or kableExtra funcions does not work on export2md resulting table.

Regards,

Isaac.

**Comment by hsbizahlenzauber** [comment]
Hello,
sorry, that I didn't realize, that it's easy like this to customize the output. So the package is even more awesome ;-)

Regards,
Thomas

**Comment by isubirana** [comment]
Perfect.

Regards,

Isaac.
