### ISSUE TITLE
Change placement of the table caption

### ISSUE THREAD

**Issue by osanzmar** [isubirana/compareGroups#22]
Hi! How can I change the placement of the caption if I have made a table in a .rmd file and have used export2md to create a pdf document? I would like to put it at the bottom of the table...
Thank you!!

**Comment by isubirana** [comment]
Unfortunately, by now it is not possible to change caption placement. So, it is placed on top and cannot be changed to be placed at the bottom. But, we hope to add this option in future versions.
Thanks for using the compareGroups package. Your feedback is very useful to improve it.

**Comment by isubirana** [comment]
After some attempts, given the way the compareGroups package functions are structured and programmed, we couldn't add the option to place the caption below the tables.
Therefore and unfortunately, by now, table captions will be placed on top and there is no option to place it below using comparGroups functions and options.
