### ISSUE TITLE
problem loading compareGroups

### ISSUE THREAD

**Issue by chymkat** [isubirana/compareGroups#23]
Dear All

I have installed compareGroups on a fresh R/rstudio for windows but I cant load it.
I have tried systemfonts and update all but no sollution.

library(compareGroups)
Error: package or namespace load failed for ‘compareGroups’ in namespaceExport(ns, exports):
undefined exports: cividis, inferno, magma, mako, plasma, rocket, turbo, viridis, viridis.map, viridisMap

**Comment by isubirana** [comment]
Can you provide the R and RStudio version you are using?

**Comment by chymkat** [comment]
Dear Isubirana
I am using the latest version of both R/rstudio.
I just have the problem solved by resolving the conflict with my onedrive by trying this recommendation.
https://medium.com/@ValidScience/how-to-fix-rstudios-package-installation-on-windows-10-c1e602bf3a1f.
