### ISSUE TITLE
Export the chi-Square test value or  F-test value,not P value

### ISSUE THREAD

**Issue by CGL5230** [isubirana/compareGroups#30]
Hi! i read the Descriptives book of compareGroups package and find the function seems like doing a chi-square test for count data. But i use the **descrTable** , i can't find the chi-Square test value. It's there anyway to export the value of chi-Squre test or F-test?

**Comment by isubirana** [comment]
Both `compareGroups` or `descrTable` report only p-values and not the associated test statistic value. The reason is that the vast majority of epidemiological studies report frequencies and p-value and not Chi-squared nor F value. Also, when performing permuted Chi-squared test, only p-value is computed.

**Comment by CGL5230** [comment]
Thanks a lot. But  i want report the chi-Square test value. Is there any way to extract the value in `compaerGroups`

**Comment by isubirana** [comment]
Alternatively, you can obtain the chi-Square values by hand. First p-values can be extracted using `getResults` function. Then, the chi-square test value can be obtained by applying `qchisq` function with the appropiate degrees of freedom.
For example, to get the chi-square association between cardiovascular event (cv), [yes/no] and smoking status (smoker) [never/current or former<1y/former >1y]:

```
library(compareGroups)
# load example data
data(regicor)
# create descriptive table
tab <- descrTable(cv ~ smoker + age, regicor)
# get p-value for the first variable (smoker)
pvals <- getResults(tab, "p.overall")[1]
# get chi-square value with appropiate degrees of freedom (df=2)
chisq.val <- qchisq(pvals, 2, lower.tail=FALSE)
chisq.val
# checking: recompute p-value using this chisq.value
1-pchisq(chisq.val,2)
```

I hope it helps.

**Comment by CGL5230** [comment]
Sure. It helps~ Thx again:)
