### ISSUE TITLE
Export to flextable

### ISSUE THREAD

**Issue by acebollada80** [isubirana/compareGroups#39]
HI!

I would like to know if there is a way to export a compareGroups object into the flextable format for easier table visualization and reporting. Is this functionality currently supported, or are there any recommended approaches to achieve this?

Thank you!

Alberto Cebollada

**Comment by isubirana** [comment]
Hi Alberto.

By default, export2md function returns and object of class kable. But if you set the format  to 'markdown', the resulting table will be of class "flextable" to which all function of this package can be applied. For example, to colour the first row to red on a descriptive table of iris data:

```
library(compareGroups)

tab <- export2md(descrTable(iris), format="markdown")
class(tab)

flextable::bg(tab,i = 1,bg = "red")
```

In summary, export2md uses knitr and kableExtra when exporting to HTML or LaTeX, and flextable when exporting to markdown or Word.

Kind regards,

Isaac.
