### ISSUE TITLE
Subset by overall p-value

### ISSUE THREAD

**Issue by tiagochst** [isubirana/compareGroups#4]
Hello,

Please, is it possible to subset the results to show only variables with overall p-value below a certain threshold ? I could not find that explicit in the vignette.

Thanks!

**Comment by isubirana** [comment]
Hi,

Although there is no specific function or argument to select significant variables, you can use the getResults to retrieve the p-values and then make use of [] to select the variables from the descriptive table. Below there is an example:

```
library(compareGroups)
data(predimed)
tab <- descrTable(event ~ ., predimed)
pvals <- getResults(tab, "p.overall")
tab[pvals<0.05]
```

By the way, we will try to incorporate a new function to do this more intuitively. 
Many thanks for your feed back.

Isaac.
