### ISSUE TITLE
Compiled Format: Argument of length zero

### ISSUE THREAD

**Issue by mutlusun** [isubirana/compareGroups#6]
Hello,

many thanks for providing the compareGroups package!

Since updating to 4.1, I have issues using the package in a RMarkdown document:
```
Error in if (compiled.format %in% c("html_document", "ioslides_presentation",  : 
  argument is of length zero
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>
```

This error occurs because I am using a child document in RMarkdown. See [this lines](https://github.com/isubirana/compareGroups/blob/c20e92eb12b8c20e1982e651efcd1a84c680fdc6/R/export2md.R#L5) in `export2md.R`. `current_input()` returns the filename of my child document. This one has no yaml header, thus `all_output_formats()` results in `NULL`.

Possible solution might be to use the `is_latex_output` and `is_html_output` from `knitr`.

Thanks for your help!

**Comment by isubirana** [comment]
Thank you very much.
Does it work if you specify format="html" explicitly when calling export2md?
Anyway, could you email me an example in order to check it? I will try to incorporate the solution you propose in next versions.

**Comment by mutlusun** [comment]
Dear @isubirana ,

thanks for your help and your investigation. Unfortunately, `format="html"` does not change anything.

Sorry, I forgot to provide a MWE. Here is one:

main.Rmd:
```
---
title: "MWE"
output: 
    html_notebook:
        toc: true
        toc_float: true
        number_sections: true
        theme: united
        highlight: tango
        code_folding: hide
---

 ``{r child = "test.Rmd"}
 ``
```

test.Rmd:
```
# MWE Test

 ``{r}
myd <- data.frame(x=rnorm(200),
                  y=factor(rep(1:2, each=100)))

tmp <- compareGroups::compareGroups(y ~ x, data=myd)
tmp <- compareGroups::createTable(tmp, show.ratio=TRUE)

compareGroups::export2md(tmp, which.table="descr")
compareGroups::export2md(tmp, which.table="avail")

rmarkdown::all_output_formats(knitr::current_input())
rmarkdown::metadata$output
knitr::knit_meta()
knitr::opts_knit$get()
knitr::is_latex_output()
knitr::is_html_output()
 ``
```

Be aware, that I had to remove a ` in the code chunks due to the styling of github.

Many thanks for your help!

**Comment by isubirana** [comment]
Finally, I could figure out what the problem was. I had to modify the internal code of export2md function in order to support Rmd files without yaml output specification, as it was the case in your example using notebook.
The updated code is, by now, on github repository. So, type the following code to install the latest compareGroups version:
remotes::install_github("isubirana/compareGroups")

Let me know if it works now.

**Comment by mutlusun** [comment]
Hello,

many thanks for your fast response! Everything is working now as intended!
