### ISSUE TITLE
Why more than 5 groups not allowed?

### ISSUE THREAD

**Issue by rushabhpatel31** [isubirana/compareGroups#7]
I am trying to get ccompareGroup createTable for data with more than 5 groups. But, I am getting error that, it is not allowed.
Is there any specific reason, why this can't be implemented.

You input will be really helpful.

**Comment by isubirana** [comment]
If you want to compare more than 5 groups, you must specify the "max.ylev" argument from "compareGroups" function to at least the number of groups you have. By default this argument is set to 5 in order to prevent from building too wide tables.

I hope it helps.

**Comment by rushabhpatel31** [comment]
Thanks isubirana :)
